-- Seed the concrete CONFIG defaults from ERD v10 section 7.10 and the
-- concurrent listing limits fixed by SRS rule BR-U01.
-- ai_daily_budget is intentionally omitted because the ERD marks it as undecided.
-- max_active_items_diamond uses -1 to represent the SRS value "unlimited".
INSERT INTO website_attributes (attr_group, attr_key, attr_value)
VALUES
  ('CONFIG', 'vnd_per_credit', '1000'),
  ('CONFIG', 'topup_min_credits', '10'),
  ('CONFIG', 'post_fee', '5'),
  ('CONFIG', 'post_display_days', '30'),
  ('CONFIG', 'post_display_days_gold', '45'),
  ('CONFIG', 'max_active_items_bronze', '3'),
  ('CONFIG', 'max_active_items_silver', '5'),
  ('CONFIG', 'max_active_items_gold', '10'),
  ('CONFIG', 'max_active_items_diamond', '-1'),
  ('CONFIG', 'edit_fee', '5'),
  ('CONFIG', 'renew_fee', '5'),
  ('CONFIG', 'renew_expired_window_days', '7'),
  ('CONFIG', 'boost_fee', '5'),
  ('CONFIG', 'boost_days', '3'),
  ('CONFIG', 'boost_max_days', '14'),
  ('CONFIG', 'boost_max_per_page', '3'),
  ('CONFIG', 'ai_search_fee', '2'),
  ('CONFIG', 'ai_free_per_day', '5'),
  ('CONFIG', 'ai_trial_uses', '1'),
  ('CONFIG', 'ai_search_timeout_seconds', '15'),
  ('CONFIG', 'chat_ai_threshold', '0.7'),
  ('CONFIG', 'chat_ai_timeout_seconds', '5'),
  ('CONFIG', 'item_ai_timeout_seconds', '20'),
  ('CONFIG', 'item_ai_retries', '1'),
  ('CONFIG', 'chat_violation_alert', '3'),
  ('CONFIG', 'item_photos_min', '3'),
  ('CONFIG', 'item_photos_max', '8'),
  ('CONFIG', 'image_max_mb', '5'),
  ('CONFIG', 'media_orphan_hours', '24'),
  ('CONFIG', 'review_sla_hours', '24'),
  ('CONFIG', 'report_hide_threshold', '3'),
  ('CONFIG', 'otp_ttl_minutes', '5'),
  ('CONFIG', 'otp_max_fails', '5'),
  ('CONFIG', 'otp_resend_seconds', '60'),
  ('CONFIG', 'unverified_account_hours', '24'),
  ('CONFIG', 'accounts_per_ip_24h', '3'),
  ('CONFIG', 'phone_change_interval_days', '30'),
  ('CONFIG', 'max_pending_requests', '5'),
  ('CONFIG', 'request_pending_days', '3'),
  ('CONFIG', 'chat_open_days', '10'),
  ('CONFIG', 'auto_confirm_days', '3'),
  ('CONFIG', 'complaint_window_days', '7'),
  ('CONFIG', 'response_window_days', '3'),
  ('CONFIG', 'daily_points_cap', '30'),
  ('CONFIG', 'payment_order_expire_minutes', '30')
ON CONFLICT (attr_group, attr_key) WHERE NOT is_deleted DO NOTHING;
